# Stage 1: Build the server
FROM node:18 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run prisma:generate
RUN npm run build

# Stage 2: Run the server
FROM node:18-slim
WORKDIR /app
COPY --from=builder /app/dist ./
COPY --from=builder /app/prisma/ ./
COPY package*.json ./
RUN npm install

# Set the command to start the server
CMD ["node", "index.js"]