# Stage 1: Build the server
FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Set the command to start the server
CMD ["npm", "start"]
# Keep the container running for an hour
# CMD ["sleep", "3600"]